##################################################################################################################
# Logs- Debug
#logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG

##################################################################################################################
# Config JPA - Ignore Database & Hibernate DDL Auto
spring.jpa.hibernate.ddl-auto=create-drop

##################################################################################################################
# Config Cache Redis - Ignora e desabilita as configurações de cache do Redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
app.redis.enabled=false

# Força o Spring a usar um mapa em memória simples, ignorando o Redis para cache
spring.cache.type=simple

# Desativavando o cache completamente
#spring.cache.type=none

##################################################################################################################
# H2 Client
spring.datasource.url=jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS picpay\\;CREATE SCHEMA IF NOT EXISTS dslistapp
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# Enable script initialization for always or embedded DBs
spring.sql.init.mode=never

# Ensure schema.sql runs BEFORE Hibernate creates tables
spring.jpa.defer-datasource-initialization=false

# Tell Hibernate to ignore import.sql
spring.jpa.properties.hibernate.hbm2ddl.import_files=none

# Show SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
