##################################################################################################################
# Logs- Debug
#logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG

##################################################################################################################
# Config JPA - Ignore Database & Hibernate DDL Auto
spring.jpa.hibernate.ddl-auto=none

##################################################################################################################
# Config Cache Redis - Ignora e desabilita as configurações de cache do Redis
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
app.redis.enabled=false

# Força o Spring a usar um mapa em memória simples, ignorando o Redis para cache
spring.cache.type=simple

# Desativavando o cache completamente
#spring.cache.type=none

##################################################################################################################
loan.customer.service.url=localhost:9094/aws_localstack/loans/customer-loans

##################################################################################################################
# H2 Database Connection
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
