##################################################################################################################
server.port=9092

##################################################################################################################
#spring.profiles.active=${APP_PROFILE:dev}
#spring.profiles.active=${APP_PROFILE:test}

spring.profiles.active=${APP_PROFILE:picpay}
#spring.profiles.active=${APP_PROFILE:itau}

#spring.profiles.active=${APP_PROFILE:emprestimo}
#spring.profiles.active=${APP_PROFILE:cripto}

##################################################################################################################
spring.jpa.open-in-view=false
cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}
address.service.base.url.apis.picpay=https://util.devi.tools/api

##################################################################################################################
# Docs - SpringDoc Swagger

# Only scan controllers residing in this base package
springdoc.packages-to-scan=com.devsuperior.dslist.controllers

# Alterar o caminho padrão do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Mudar a ordem de exibição das tags/controladores (ex: alfabética)
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method

# Desativar o Swagger UI em ambiente de produção (exemplo)
# springdoc.swagger-ui.enabled=false

##################################################################################################################
# AWS Service - SpringCloud

spring.cloud.aws.region.static=sa-east-1
# Optional: Use if you are using LocalStack for local testing
spring.cloud.aws.endpoint=http://localhost:4566

##################################################################################################################
# AWS SQS Service - Consumers
fila.producer.name.sqs-solicitar-regitro-movimento-cliente=sqs-solicitar-regitro-movimento-cliente

##################################################################################################################
# URLS Externas
loan.customer.service.url=localhost:9094/aws_localstack/loans/customer-loans

