# ###### -------------------------------------------------------------------------------------
# --

spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

# ###### -------------------------------------------------------------------------------------
# -- Database PostgreSQL
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/dslistapp
spring.datasource.hikari.schema=dslistapp
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.tomcat.validation-query=SELECT 1

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# ###### -------------------------------------------------------------------------------------
# - Database Cache - Redis
spring.cache.type=redis
spring.data.redis.connect-timeout=6000
spring.data.redis.database=0
spring.data.redis.ssl.enabled=false
spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.password=Redis2025!

# ###### -------------------------------------------------------------------------------------